const mongoose = require("mongoose");
const Admin = require("../../src/mongoose/models/admin");
const Players = require("../../src/mongoose/models/players");
const jwt = require("jsonwebtoken");

const adminObjectID = new mongoose.Types.ObjectId();

const admin = {
    _id: adminObjectID,
    name: "IPL Admin",
    password: "Ipl@1234",
    tokens: [
        {
            token: jwt.sign({_id: adminObjectID}, "xeEo2M0ol8CeWr7Nw2g2GjH8QEUK4dyyKCHi4TYJK6znm5fuAHIIPHSQ5YvdVcLlnaxppN64xK6xbhRileWvIlzCEqrBMCiITD8z"),
        }
    ]
}

const players = [
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player one",
        age: 23,
        type: "All-rounder",
        bats: "Left",
        bowls: "Right",
        bowling_style: "Spin",
        bat_avg: 43.65,
        bowl_avg: 11.1,
        bat_strike_rate: 186.50,
        bowl_strike_rate: 15.12,
        catches: 10,
        runouts: 2,
        thirtys: 15,
        fifties: 5,
        centuries: 1,
        three_WH: 10,
        five_WH: 2,
        highest_runs: 123,
        best_bowling: "5/12",
        overseas: true,
        displayed_count: 1,
        unsold: false,
        base_price: 10000000,
        sold_price: 75000000,
        bought_by: "CSK",
        bidded_by: "CSK",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player two",
        age: 27,
        type: "Batsman",
        bats: "Left",
        bowls: "NA",
        bowling_style: "NA",
        bat_avg: 32.32,
        bowl_avg: 0.0,
        bat_strike_rate: 124.76,
        bowl_strike_rate: 0.0,
        catches: 15,
        runouts: 3,
        thirtys: 24,
        fifties: 8,
        centuries: 0,
        three_WH: 0,
        five_WH: 0,
        highest_runs: 84,
        best_bowling: "",
        overseas: false,
        displayed_count: 1,
        unsold: false,
        base_price: 5000000,
        sold_price: 15000000,
        bought_by: "CSK",
        bidded_by: "CSK",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player three",
        age: 20,
        type: "Batsman",
        bats: "Right",
        bowls: "NA",
        bowling_style: "NA",
        bat_avg: 49.34,
        bowl_avg: 0.0,
        bat_strike_rate: 135.7,
        bowl_strike_rate: 0.0,
        catches: 87,
        runouts: 15,
        thirtys: 84,
        fifties: 42,
        centuries: 2,
        three_WH: 0,
        five_WH: 0,
        highest_runs: 128,
        best_bowling: "",
        overseas: false,
        displayed_count: 1,
        unsold: false,
        base_price: 10000000,
        sold_price: 95000000,
        bought_by: "CSK",
        bidded_by: "CSK",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player four",
        age: 22,
        type: "All-rounder",
        bats: "Left",
        bowls: "Left",
        bowling_style: "Fast",
        bat_avg: 32.12,
        bowl_avg: 12.12,
        bat_strike_rate: 198.23,
        bowl_strike_rate: 16.2,
        catches: 12,
        runouts: 1,
        thirtys: 5,
        fifties: 2,
        centuries: 0,
        three_WH: 3,
        five_WH: 1,
        highest_runs: 67,
        best_bowling: "6/16",
        overseas: true,
        displayed_count: 1,
        unsold: false,
        base_price: 15000000,
        sold_price: 65000000,
        bought_by: "CSK",
        bidded_by: "CSK",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player five",
        age: 29,
        type: "Bowler",
        bats: "Right",
        bowls: "Right",
        bowling_style: "Medium",
        bat_avg: 0.0,
        bowl_avg: 10.56,
        bat_strike_rate: 0.0,
        bowl_strike_rate: 13.87,
        catches: 6,
        runouts: 0,
        thirtys: 0,
        fifties: 0,
        centuries: 0,
        three_WH: 4,
        five_WH: 0,
        highest_runs: 0,
        best_bowling: "4/8",
        overseas: false,
        displayed_count: 1,
        unsold: false,
        base_price: 2000000,
        sold_price: 12000000,
        bought_by: "CSK",
        bidded_by: "CSK",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player six",
        age: 18,
        type: "Batsman",
        bats: "Left",
        bowls: "NA",
        bowling_style: "NA",
        bat_avg: 0.0,
        bowl_avg: 0.0,
        bat_strike_rate: 0.0,
        bowl_strike_rate: 0.0,
        catches: 0,
        runouts: 0,
        thirtys: 0,
        fifties: 0,
        centuries: 0,
        three_WH: 0,
        five_WH: 0,
        highest_runs: 0,
        best_bowling: "",
        overseas: false,
        displayed_count: 0,
        unsold: true,
        base_price: 1000000,
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player seven",
        age: 32,
        type: "Bowler",
        bats: "Right",
        bowls: "Right",
        bowling_style: "Leg-spin",
        bat_avg: 12.2,
        bowl_avg: 13.12,
        bat_strike_rate: 78.2,
        bowl_strike_rate: 9.56,
        catches: 43,
        runouts: 3,
        thirtys: 0,
        fifties: 0,
        centuries: 0,
        three_WH: 13,
        five_WH: 2,
        highest_runs: 28,
        best_bowling: "5/15",
        overseas: false,
        displayed_count: 0,
        unsold: true,
        base_price: 10000000,
        sold_price: 20000000,
        bidded_by: "RCB",
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player eight",
        age: 24,
        type: "Batsman",
        bats: "Left",
        bowls: "NA",
        bowling_style: "NA",
        bat_avg: 32.23,
        bowl_avg: 0.0,
        bat_strike_rate: 143.34,
        bowl_strike_rate: 0.0,
        catches: 22,
        runouts: 3,
        thirtys: 11,
        fifties: 5,
        centuries: 0,
        three_WH: 0,
        five_WH: 0,
        highest_runs: 98,
        best_bowling: "",
        overseas: true,
        displayed_count: 0,
        unsold: true,
        base_price: 12000000,
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player nine",
        age: 21,
        type: "Bowler",
        bats: "Left",
        bowls: "Left",
        bowling_style: "Fast",
        bat_avg: 0.0,
        bowl_avg: 17.12,
        bat_strike_rate: 0.0,
        bowl_strike_rate: 11.23,
        catches: 7,
        runouts: 0,
        thirtys: 0,
        fifties: 0,
        centuries: 0,
        three_WH: 4,
        five_WH: 0,
        highest_runs: 0,
        best_bowling: "4/24",
        overseas: true,
        displayed_count: 0,
        unsold: true,
        base_price: 5000000,
    },
    {
        _id: new mongoose.Types.ObjectId(),
        name: "player ten",
        age: 30,
        type: "Bowler",
        bats: "Right",
        bowls: "Right",
        bowling_style: "Medium",
        bat_avg: 36.13,
        bowl_avg: 22.13,
        bat_strike_rate: 132.45,
        bowl_strike_rate: 19.2,
        catches: 12,
        runouts: 1,
        thirtys: 4,
        fifties: 0,
        centuries: 0,
        three_WH: 4,
        five_WH: 0,
        highest_runs: 48,
        best_bowling: "3/13",
        overseas: true,
        displayed_count: 0,
        unsold: true,
        base_price: 20000000,
    }
]

const setUpDatabase = async () => {
    await Admin.deleteMany();
    await Players.deleteMany();
    await new Admin(admin).save();
    for(let i = 0; i < players.length; i++) {
        await new Players(players[i]).save();
    }
}

module.exports = {
    admin,
    players,
    setUpDatabase
}